version: '2'
services:
  web:
    image: 'nginx:alpine'
    container_name: ${APP_NAME}-web
    depends_on:
      - php-fpm
    volumes:
      - './docker-assets/nginx/:/etc/nginx/conf.d'
      - './ :/var/www'
    ports:
      - '98:80'
  php-fpm:
    build: ./docker-assets/php-fpm
    container_name: ${APP_NAME}-fpm
    volumes:
      - './:/var/www:cached'
